#!/bin/sh
#start the service for file transfer
nfs/fusionFS/src/ffsnet/ffsnetd 2>&1 1>/dev/null &  

#start the service for ZHT server
nfs/fusionFS/src/zht/bin/server_zht 50000 nfs/fusionFS/src/zht/neighbor nfs/fusionFS/src/zht/zht.cfg TCP 2>&1 1>/dev/null &
